$(document).ready(function(){
			$(".new_list_box_img1").mouseover(function(){
				$(".new_list_box1").show();
			});
			$(".new_list_box_img1").mouseout(function(){
				$(".new_list_box1").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img2").mouseover(function(){
				$(".new_list_box2").show();
			});
			$(".new_list_box_img2").mouseout(function(){
				$(".new_list_box2").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img3").mouseover(function(){
				$(".new_list_box3").show();
			});
			$(".new_list_box_img3").mouseout(function(){
				$(".new_list_box3").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img4").mouseover(function(){
				$(".new_list_box4").show();
			});
			$(".new_list_box_img4").mouseout(function(){
				$(".new_list_box4").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img5").mouseover(function(){
				$(".new_list_box5").show();
			});
			$(".new_list_box_img5").mouseout(function(){
				$(".new_list_box5").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img6").mouseover(function(){
				$(".new_list_box6").show();
			});
			$(".new_list_box_img6").mouseout(function(){
				$(".new_list_box6").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img7").mouseover(function(){
				$(".new_list_box7").show();
			});
			$(".new_list_box_img7").mouseout(function(){
				$(".new_list_box7").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img8").mouseover(function(){
				$(".new_list_box8").show();
			});
			$(".new_list_box_img8").mouseout(function(){
				$(".new_list_box8").hide();
			});
		});
		$(document).ready(function(){
			$(".new_list_box_img9").mouseover(function(){
				$(".new_list_box9").show();
			});
			$(".new_list_box_img9").mouseout(function(){
				$(".new_list_box9").hide();
			});
		});